web:
  image: nginx:latest
  ports:
    - "8080:80"
  volumes:
    - ./www:/code
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
  links:
    - php

php:
  build: .
  volumes:
    - ./www:/code
  environment:
    XDEBUG_CONFIG: remote_host=host.docker.internal
  links:
    - mysql
    - maildev

mysql:
  image: mysql:5.7.13
  ports:
    - "3306:3306"
  environment:
    MYSQL_DATABASE: Restaurante
    MYSQL_PASSWORD: test
    MYSQL_ROOT_PASSWORD: test

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - mysql:db
  ports:
    - "8082:80"
  environment:
    - PMA_USER=root
    - PMA_PASSWORD=password
    - PHP_UPLOAD_MAX_FILESIZE=100MB

maildev:
  image: djfarrelly/maildev
  ports:
   - "8081:80"
